// Auto-generated by scripts/process-images.mjs
// Do not edit manually — re-run: node scripts/process-images.mjs

export interface SiteImage {
  path: string;
  alt: string;
  name: string;
  type?: string;
}

export const HERO_IMAGES: SiteImage[] = [
  {
    "path": "/img/hero/hero-cedar-privacy-fence-twomens-crew.webp",
    "alt": "TWOMENS crew member inspecting tall cedar privacy fence installation in Delaware",
    "name": "hero-cedar-privacy-fence-twomens-crew"
  },
  {
    "path": "/img/hero/hero-aluminum-ornamental-fence-green-lawn.webp",
    "alt": "Black aluminum ornamental fence installation on lush green property in Delaware",
    "name": "hero-aluminum-ornamental-fence-green-lawn"
  },
  {
    "path": "/img/hero/hero-chain-link-fence-installation-field.webp",
    "alt": "TWOMENS crew installing galvanized chain link fence on large commercial property",
    "name": "hero-chain-link-fence-installation-field"
  },
  {
    "path": "/img/hero/hero-vinyl-privacy-fence-long-run.webp",
    "alt": "Long run of white vinyl privacy fence installation with blue sky in Delaware",
    "name": "hero-vinyl-privacy-fence-long-run"
  }
];

export const OG_IMAGE = "/img/og-image.webp";

export const GALLERY_IMAGES: (SiteImage & { type: string })[] = [
  {
    "path": "/img/gallery/gallery-01-cedar-privacy-fence.webp",
    "alt": "Cedar privacy fence installation by TWOMENS Fence in Delaware",
    "name": "gallery-01-cedar-privacy-fence",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-02-wood-fence-with-gate.webp",
    "alt": "Wood privacy fence with custom gate installation",
    "name": "gallery-02-wood-fence-with-gate",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-03-wood-privacy-backyard.webp",
    "alt": "Wood privacy fence along residential backyard property",
    "name": "gallery-03-wood-privacy-backyard",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-04-porch-railing-complete.webp",
    "alt": "Custom wood porch railing with fence in background",
    "name": "gallery-04-porch-railing-complete",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-05-porch-railing-front.webp",
    "alt": "Wood porch railing installation on Delaware home",
    "name": "gallery-05-porch-railing-front",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-06-vinyl-privacy-long.webp",
    "alt": "White vinyl privacy fence long installation run",
    "name": "gallery-06-vinyl-privacy-long",
    "type": "Vinyl"
  },
  {
    "path": "/img/gallery/gallery-07-vinyl-privacy-residential.webp",
    "alt": "White vinyl privacy fence on residential property",
    "name": "gallery-07-vinyl-privacy-residential",
    "type": "Vinyl"
  },
  {
    "path": "/img/gallery/gallery-08-vinyl-privacy-house.webp",
    "alt": "Vinyl privacy fence alongside Delaware home",
    "name": "gallery-08-vinyl-privacy-house",
    "type": "Vinyl"
  },
  {
    "path": "/img/gallery/gallery-09-vinyl-picket-house.webp",
    "alt": "White vinyl picket fence around residential yard",
    "name": "gallery-09-vinyl-picket-house",
    "type": "Vinyl"
  },
  {
    "path": "/img/gallery/gallery-10-chainlink-commercial-sports.webp",
    "alt": "Black chain link fence at sports facility",
    "name": "gallery-10-chainlink-commercial-sports",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-11-chainlink-black-commercial.webp",
    "alt": "Black vinyl-coated chain link fence commercial installation",
    "name": "gallery-11-chainlink-black-commercial",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-12-chainlink-galvanized-field.webp",
    "alt": "Galvanized chain link fence installation on large property",
    "name": "gallery-12-chainlink-galvanized-field",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-13-chainlink-winter.webp",
    "alt": "Chain link fence in winter conditions",
    "name": "gallery-13-chainlink-winter",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-14-aluminum-ornamental.webp",
    "alt": "Black aluminum ornamental spear top fence",
    "name": "gallery-14-aluminum-ornamental",
    "type": "Aluminum"
  },
  {
    "path": "/img/gallery/gallery-15-aluminum-landscape.webp",
    "alt": "Aluminum ornamental fence on landscaped property",
    "name": "gallery-15-aluminum-landscape",
    "type": "Aluminum"
  },
  {
    "path": "/img/gallery/gallery-16-commercial-enclosure.webp",
    "alt": "Commercial dumpster enclosure installation",
    "name": "gallery-16-commercial-enclosure",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-17-commercial-enclosure-winter.webp",
    "alt": "Commercial chain link enclosure at business",
    "name": "gallery-17-commercial-enclosure-winter",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-18-commercial-enclosure-night.webp",
    "alt": "Completed commercial enclosure at night",
    "name": "gallery-18-commercial-enclosure-night",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-19-crew-building-railing.webp",
    "alt": "TWOMENS crew building custom porch railing",
    "name": "gallery-19-crew-building-railing",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-20-crew-digging-posts.webp",
    "alt": "Crew setting post holes for fence installation",
    "name": "gallery-20-crew-digging-posts",
    "type": "Wood"
  }
];

export const SERVICE_IMAGES = {
  wood: [
  {
    "path": "/img/services/wood-cedar-privacy-fence-tall.webp",
    "alt": "Tall cedar privacy fence installation by TWOMENS Fence in Delaware",
    "name": "wood-cedar-privacy-fence-tall"
  },
  {
    "path": "/img/services/wood-privacy-fence-with-gate.webp",
    "alt": "Pressure-treated wood privacy fence with gate installation in residential backyard",
    "name": "wood-privacy-fence-with-gate"
  },
  {
    "path": "/img/services/wood-privacy-fence-backyard.webp",
    "alt": "New wood privacy fence installed along residential backyard property line",
    "name": "wood-privacy-fence-backyard"
  },
  {
    "path": "/img/services/wood-porch-railing-front.webp",
    "alt": "Custom wood porch railing installation on residential front porch",
    "name": "wood-porch-railing-front"
  },
  {
    "path": "/img/services/wood-porch-railing-complete.webp",
    "alt": "Completed wood porch railing with wood privacy fence in background",
    "name": "wood-porch-railing-complete"
  },
  {
    "path": "/img/services/wood-porch-railing-crew-working.webp",
    "alt": "TWOMENS crew installing custom wood porch railing on Delaware home",
    "name": "wood-porch-railing-crew-working"
  },
  {
    "path": "/img/services/wood-porch-railing-crew-action.webp",
    "alt": "Fence installation crew building wood railing on residential porch",
    "name": "wood-porch-railing-crew-action"
  },
  {
    "path": "/img/services/wood-cedar-fence-perspective.webp",
    "alt": "Cedar wood fence installation showing straight fence line and quality craftsmanship",
    "name": "wood-cedar-fence-perspective"
  }
],
  vinyl: [
  {
    "path": "/img/services/vinyl-white-privacy-fence-long.webp",
    "alt": "Long white vinyl privacy fence installation on open property in Delaware",
    "name": "vinyl-white-privacy-fence-long"
  },
  {
    "path": "/img/services/vinyl-white-privacy-fence-residential.webp",
    "alt": "White vinyl privacy fence installed along residential property line",
    "name": "vinyl-white-privacy-fence-residential"
  },
  {
    "path": "/img/services/vinyl-white-privacy-fence-house.webp",
    "alt": "White vinyl privacy fence installation alongside Delaware home",
    "name": "vinyl-white-privacy-fence-house"
  },
  {
    "path": "/img/services/vinyl-white-picket-fence-house.webp",
    "alt": "White vinyl picket fence installation around residential property with yard",
    "name": "vinyl-white-picket-fence-house"
  },
  {
    "path": "/img/services/vinyl-fence-materials-prep.webp",
    "alt": "Vinyl fence materials being prepared for installation on job site",
    "name": "vinyl-fence-materials-prep"
  }
],
  chainlink: [
  {
    "path": "/img/services/chainlink-galvanized-crew-install.webp",
    "alt": "Crew installing galvanized chain link fence on large property in Delaware",
    "name": "chainlink-galvanized-crew-install"
  },
  {
    "path": "/img/services/chainlink-black-vinyl-coated-commercial.webp",
    "alt": "Black vinyl-coated chain link fence with materials staged for commercial installation",
    "name": "chainlink-black-vinyl-coated-commercial"
  },
  {
    "path": "/img/services/chainlink-black-commercial-sports.webp",
    "alt": "Black chain link fence installation at commercial sports facility in Delaware",
    "name": "chainlink-black-commercial-sports"
  },
  {
    "path": "/img/services/chainlink-black-vinyl-coated-long.webp",
    "alt": "Long run of black vinyl-coated chain link fence around commercial property",
    "name": "chainlink-black-vinyl-coated-long"
  },
  {
    "path": "/img/services/chainlink-black-winter-snow.webp",
    "alt": "Black vinyl-coated chain link fence installation in winter conditions",
    "name": "chainlink-black-winter-snow"
  },
  {
    "path": "/img/services/chainlink-commercial-fence-property.webp",
    "alt": "Commercial chain link fence with barbed wire on business property",
    "name": "chainlink-commercial-fence-property"
  },
  {
    "path": "/img/services/chainlink-posts-setting.webp",
    "alt": "Metal fence posts being set for chain link fence installation",
    "name": "chainlink-posts-setting"
  },
  {
    "path": "/img/services/chainlink-galvanized-field-long.webp",
    "alt": "Galvanized chain link fence stretching across large open field",
    "name": "chainlink-galvanized-field-long"
  }
],
  aluminum: [
  {
    "path": "/img/services/aluminum-black-ornamental-spear-top.webp",
    "alt": "Black aluminum ornamental spear top fence installation in Delaware",
    "name": "aluminum-black-ornamental-spear-top"
  },
  {
    "path": "/img/services/aluminum-ornamental-fence-landscape.webp",
    "alt": "Black aluminum ornamental fence on beautifully landscaped property",
    "name": "aluminum-ornamental-fence-landscape"
  },
  {
    "path": "/img/services/aluminum-black-fence-posts-install.webp",
    "alt": "Black aluminum fence posts being installed with equipment on site",
    "name": "aluminum-black-fence-posts-install"
  }
],
} as const;

export const COMMERCIAL_IMAGES: SiteImage[] = [
  {
    "path": "/img/commercial/commercial-dumpster-enclosure-chainlink.webp",
    "alt": "Commercial chain link dumpster enclosure installation in parking lot",
    "name": "commercial-dumpster-enclosure-chainlink"
  },
  {
    "path": "/img/commercial/commercial-dumpster-enclosure-winter.webp",
    "alt": "Commercial chain link enclosure installed at business property in winter",
    "name": "commercial-dumpster-enclosure-winter"
  },
  {
    "path": "/img/commercial/commercial-chainlink-enclosure-nighttime.webp",
    "alt": "Completed commercial chain link enclosure at night",
    "name": "commercial-chainlink-enclosure-nighttime"
  },
  {
    "path": "/img/commercial/commercial-chainlink-dumpster-gates.webp",
    "alt": "Commercial chain link dumpster enclosure with swing gates",
    "name": "commercial-chainlink-dumpster-gates"
  },
  {
    "path": "/img/commercial/commercial-fence-posts-concrete.webp",
    "alt": "Commercial fence post installation with concrete footings along building",
    "name": "commercial-fence-posts-concrete"
  },
  {
    "path": "/img/commercial/commercial-fence-posts-alley.webp",
    "alt": "Commercial fence post setting in alley with concrete base",
    "name": "commercial-fence-posts-alley"
  },
  {
    "path": "/img/commercial/commercial-posts-bracing-alley.webp",
    "alt": "Commercial fence posts with bracing along brick building",
    "name": "commercial-posts-bracing-alley"
  },
  {
    "path": "/img/commercial/commercial-post-install-ladder.webp",
    "alt": "Commercial fence post installation with work truck and equipment",
    "name": "commercial-post-install-ladder"
  }
];

export const CREW_IMAGES: SiteImage[] = [
  {
    "path": "/img/crew/crew-digging-post-holes.webp",
    "alt": "TWOMENS fence crew digging post holes for new fence installation",
    "name": "crew-digging-post-holes"
  },
  {
    "path": "/img/crew/crew-building-porch-railing.webp",
    "alt": "TWOMENS construction crew building custom porch railing",
    "name": "crew-building-porch-railing"
  },
  {
    "path": "/img/crew/crew-working-railing.webp",
    "alt": "Two crew members working together on porch railing installation",
    "name": "crew-working-railing"
  },
  {
    "path": "/img/crew/crew-deck-demolition.webp",
    "alt": "TWOMENS crew performing deck demolition and removal",
    "name": "crew-deck-demolition"
  }
];
