// Auto-generated by scripts/process-images.mjs
// Do not edit manually — re-run: node scripts/process-images.mjs

export interface SiteImage {
  path: string;
  alt: string;
  name: string;
  type?: string;
}

export const HERO_IMAGES: SiteImage[] = [
  {
    "path": "/img/hero/hero-cedar-privacy-fence-twomens-crew.webp",
    "alt": "TWOMENS crew member inspecting tall cedar privacy fence installation in Delaware",
    "name": "hero-cedar-privacy-fence-twomens-crew"
  },
  {
    "path": "/img/gallery/gallery-15-aluminum-landscape.webp",
    "alt": "Black aluminum ornamental fence installation on lush green property in Delaware",
    "name": "hero-aluminum-ornamental-fence-green-lawn"
  },
  {
    "path": "/img/hero/hero-chain-link-fence-installation-field.webp",
    "alt": "TWOMENS crew installing galvanized chain link fence on large commercial property",
    "name": "hero-chain-link-fence-installation-field"
  },
  {
    "path": "/img/hero/hero-vinyl-privacy-fence-long-run.webp",
    "alt": "Long run of white vinyl privacy fence installation with blue sky in Delaware",
    "name": "hero-vinyl-privacy-fence-long-run"
  }
];

export const OG_IMAGE = "/img/hero/hero-cedar-privacy-fence-twomens-crew.webp";

export const GALLERY_IMAGES: (SiteImage & { type: string })[] = [
  {
    "path": "/img/gallery/gallery-01-cedar-privacy-fence.webp",
    "alt": "Cedar privacy fence installation by TWOMENS Fence in Delaware",
    "name": "gallery-01-cedar-privacy-fence",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-02-wood-fence-with-gate.webp",
    "alt": "Wood privacy fence with custom gate installation",
    "name": "gallery-02-wood-fence-with-gate",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-03-wood-privacy-backyard.webp",
    "alt": "Wood privacy fence along residential backyard property",
    "name": "gallery-03-wood-privacy-backyard",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-04-porch-railing-complete.webp",
    "alt": "Custom wood porch railing with fence in background",
    "name": "gallery-04-porch-railing-complete",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-06-vinyl-privacy-long.webp",
    "alt": "White vinyl privacy fence long installation run",
    "name": "gallery-06-vinyl-privacy-long",
    "type": "Vinyl"
  },
  {
    "path": "/img/gallery/gallery-07-vinyl-privacy-residential.webp",
    "alt": "White vinyl privacy fence on residential property",
    "name": "gallery-07-vinyl-privacy-residential",
    "type": "Vinyl"
  },
  {
    "path": "/img/gallery/gallery-08-vinyl-privacy-house.webp",
    "alt": "Vinyl privacy fence alongside Delaware home",
    "name": "gallery-08-vinyl-privacy-house",
    "type": "Vinyl"
  },
  {
    "path": "/img/gallery/gallery-09-vinyl-picket-house.webp",
    "alt": "White vinyl picket fence around residential yard",
    "name": "gallery-09-vinyl-picket-house",
    "type": "Vinyl"
  },
  {
    "path": "/img/gallery/gallery-10-chainlink-commercial-sports.webp",
    "alt": "Black chain link fence at sports facility",
    "name": "gallery-10-chainlink-commercial-sports",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-11-chainlink-black-commercial.webp",
    "alt": "Black vinyl-coated chain link fence commercial installation",
    "name": "gallery-11-chainlink-black-commercial",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-12-chainlink-galvanized-field.webp",
    "alt": "Galvanized chain link fence installation on large property",
    "name": "gallery-12-chainlink-galvanized-field",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-13-chainlink-winter.webp",
    "alt": "Chain link fence in winter conditions",
    "name": "gallery-13-chainlink-winter",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-14-aluminum-ornamental.webp",
    "alt": "Black aluminum ornamental spear top fence",
    "name": "gallery-14-aluminum-ornamental",
    "type": "Aluminum"
  },
  {
    "path": "/img/gallery/gallery-15-aluminum-landscape.webp",
    "alt": "Aluminum ornamental fence on landscaped property",
    "name": "gallery-15-aluminum-landscape",
    "type": "Aluminum"
  },
  {
    "path": "/img/gallery/gallery-16-commercial-enclosure.webp",
    "alt": "Commercial dumpster enclosure installation",
    "name": "gallery-16-commercial-enclosure",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-17-commercial-enclosure-winter.webp",
    "alt": "Commercial chain link enclosure at business",
    "name": "gallery-17-commercial-enclosure-winter",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-18-commercial-enclosure-night.webp",
    "alt": "Completed commercial enclosure at night",
    "name": "gallery-18-commercial-enclosure-night",
    "type": "Chain Link"
  },
  {
    "path": "/img/gallery/gallery-19-crew-building-railing.webp",
    "alt": "TWOMENS crew building custom porch railing",
    "name": "gallery-19-crew-building-railing",
    "type": "Wood"
  },
  {
    "path": "/img/gallery/gallery-20-crew-digging-posts.webp",
    "alt": "Crew setting post holes for fence installation",
    "name": "gallery-20-crew-digging-posts",
    "type": "Wood"
  },
  { "path": "/img/gallery/gallery-21-fence-project.webp", "alt": "Wood deck railing demolition and replacement project", "name": "gallery-21-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-22-fence-project.webp", "alt": "TWOMENS crew installing chain link fence on commercial property", "name": "gallery-22-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-23-fence-project.webp", "alt": "Chain link dumpster enclosure at commercial building", "name": "gallery-23-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-24-fence-project.webp", "alt": "Pressure-treated wood deck stairs and railing installation", "name": "gallery-24-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-25-fence-project.webp", "alt": "Chain link dumpster enclosure in commercial parking lot", "name": "gallery-25-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-26-fence-project.webp", "alt": "Chain link gate installation at commercial building", "name": "gallery-26-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-27-fence-project.webp", "alt": "Galvanized chain link fence along large property in Delaware", "name": "gallery-27-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-28-fence-project.webp", "alt": "Vinyl fence posts being set in snowy winter conditions", "name": "gallery-28-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-29-fence-project.webp", "alt": "Vinyl dumpster enclosure at commercial property", "name": "gallery-29-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-30-fence-project.webp", "alt": "TWOMENS crew installing chain link fence in parking lot", "name": "gallery-30-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-31-fence-project.webp", "alt": "Composite deck build with railing in progress", "name": "gallery-31-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-32-fence-project.webp", "alt": "Chain link gate near commercial bus depot", "name": "gallery-32-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-33-fence-project.webp", "alt": "Chain link dumpster enclosure installation", "name": "gallery-33-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-34-fence-project.webp", "alt": "White vinyl picket fence in residential front yard", "name": "gallery-34-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-35-fence-project.webp", "alt": "Black vinyl-coated chain link fence in winter", "name": "gallery-35-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-36-fence-project.webp", "alt": "Chain link fence posts being set in open field", "name": "gallery-36-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-37-fence-project.webp", "alt": "White vinyl privacy fence installed in backyard", "name": "gallery-37-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-38-fence-project.webp", "alt": "Deck footings and foundation preparation", "name": "gallery-38-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-39-fence-project.webp", "alt": "Old wood deck before renovation and removal", "name": "gallery-39-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-40-fence-project.webp", "alt": "Wood deck demolition in progress by TWOMENS crew", "name": "gallery-40-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-41-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure with privacy slats", "name": "gallery-41-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-42-fence-project.webp", "alt": "Black aluminum ornamental fence along sloped residential yard", "name": "gallery-42-fence-project", "type": "Aluminum" },
  { "path": "/img/gallery/gallery-43-fence-project.webp", "alt": "Galvanized chain link enclosure panel in commercial parking lot", "name": "gallery-43-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-44-fence-project.webp", "alt": "Black vinyl-coated chain link fence posts in snowy conditions", "name": "gallery-44-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-45-fence-project.webp", "alt": "Commercial site preparation along parking lot wall", "name": "gallery-45-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-46-fence-project.webp", "alt": "Chain link framework being installed at commercial building in winter", "name": "gallery-46-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-47-fence-project.webp", "alt": "Galvanized chain link fence along overgrown property line", "name": "gallery-47-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-48-fence-project.webp", "alt": "White vinyl privacy fence installed at beachfront property in Delaware", "name": "gallery-48-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-49-fence-project.webp", "alt": "White vinyl privacy fence with gate at residential backyard", "name": "gallery-49-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-50-fence-project.webp", "alt": "White vinyl privacy fence along residential property in winter", "name": "gallery-50-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-51-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure with privacy slats", "name": "gallery-51-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-52-fence-project.webp", "alt": "Crew installing chain link dumpster enclosure at commercial property", "name": "gallery-52-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-53-fence-project.webp", "alt": "Black vinyl-coated chain link fence along snowy property line", "name": "gallery-53-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-54-fence-project.webp", "alt": "Elevated pressure-treated wood deck with stairs and railing", "name": "gallery-54-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-55-fence-project.webp", "alt": "Composite deck with white vinyl railing nearing completion", "name": "gallery-55-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-56-fence-project.webp", "alt": "Commercial bollard installation at restaurant parking lot", "name": "gallery-56-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-57-fence-project.webp", "alt": "Fence posts being set along residential property with pool", "name": "gallery-57-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-58-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure in commercial lot", "name": "gallery-58-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-59-fence-project.webp", "alt": "Deck planner design blueprint for custom deck project", "name": "gallery-59-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-60-fence-project.webp", "alt": "Galvanized chain link rolling gate at commercial property", "name": "gallery-60-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-61-fence-project.webp", "alt": "Galvanized chain link fence being installed along rural property", "name": "gallery-61-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-62-fence-project.webp", "alt": "Commercial fence post installation along brick wall in parking lot", "name": "gallery-62-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-63-fence-project.webp", "alt": "Horizontal wood-look composite privacy fence with dark metal posts", "name": "gallery-63-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-64-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure completed at night in winter", "name": "gallery-64-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-65-fence-project.webp", "alt": "White vinyl privacy fence being installed along residential property", "name": "gallery-65-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-66-fence-project.webp", "alt": "Galvanized chain link rolling cantilever gate at commercial lot", "name": "gallery-66-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-67-fence-project.webp", "alt": "Chain link backstop installation at sports field in Delaware", "name": "gallery-67-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-68-fence-project.webp", "alt": "Galvanized chain link fence along road and property line", "name": "gallery-68-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-69-fence-project.webp", "alt": "Post hole being measured for fence installation", "name": "gallery-69-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-70-fence-project.webp", "alt": "Commercial fence posts installed along brick building wall", "name": "gallery-70-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-71-fence-project.webp", "alt": "White vinyl privacy fence with gate along side of house", "name": "gallery-71-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-72-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure with privacy slats in urban lot", "name": "gallery-72-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-73-fence-project.webp", "alt": "Chain link fence materials staged along commercial building", "name": "gallery-73-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-74-fence-project.webp", "alt": "Elevated deck with railing under construction by TWOMENS crew", "name": "gallery-74-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-75-fence-project.webp", "alt": "Black aluminum ornamental fence on retaining wall at commercial property", "name": "gallery-75-fence-project", "type": "Aluminum" },
  { "path": "/img/gallery/gallery-76-fence-project.webp", "alt": "White vinyl privacy fence with gate installed in winter", "name": "gallery-76-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-77-fence-project.webp", "alt": "Chain link fence installation near wind turbine on rural property", "name": "gallery-77-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-78-fence-project.webp", "alt": "Crew digging fence line in snow for vinyl fence installation", "name": "gallery-78-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-79-fence-project.webp", "alt": "White vinyl privacy fence installed along large property", "name": "gallery-79-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-80-fence-project.webp", "alt": "Pressure-treated wood privacy fence in residential backyard", "name": "gallery-80-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-81-fence-project.webp", "alt": "Black aluminum ornamental fence with gate at commercial property", "name": "gallery-81-fence-project", "type": "Aluminum" },
  { "path": "/img/gallery/gallery-82-fence-project.webp", "alt": "Galvanized chain link fence along road near historic building", "name": "gallery-82-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-83-fence-project.webp", "alt": "Fence posts being set at commercial bus depot property", "name": "gallery-83-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-84-fence-project.webp", "alt": "Vinyl fence posts being set at beachfront property", "name": "gallery-84-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-85-fence-project.webp", "alt": "Long white vinyl privacy fence along residential property in winter", "name": "gallery-85-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-86-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure with privacy slats in urban alley", "name": "gallery-86-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-87-fence-project.webp", "alt": "White vinyl privacy fence with gate between houses with landscaping", "name": "gallery-87-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-88-fence-project.webp", "alt": "TWOMENS crew demolishing old wooden deck and stairs", "name": "gallery-88-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-89-fence-project.webp", "alt": "Black vinyl-coated chain link fence around sports court in new development", "name": "gallery-89-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-90-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure being installed in winter", "name": "gallery-90-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-91-fence-project.webp", "alt": "White vinyl privacy fence enclosing large backyard with shed", "name": "gallery-91-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-92-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure with gates in parking lot", "name": "gallery-92-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-93-fence-project.webp", "alt": "Pressure-treated wood deck joists and framing under construction", "name": "gallery-93-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-94-fence-project.webp", "alt": "Chain link fence framework being installed at commercial lot in winter", "name": "gallery-94-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-95-fence-project.webp", "alt": "Tan and white vinyl privacy fence along side of residential house", "name": "gallery-95-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-96-fence-project.webp", "alt": "Crew installing galvanized chain link dumpster enclosure", "name": "gallery-96-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-97-fence-project.webp", "alt": "Deck ledger board and ZIP System flashing being installed", "name": "gallery-97-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-98-fence-project.webp", "alt": "White vinyl dumpster enclosure at school district building", "name": "gallery-98-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-99-fence-project.webp", "alt": "Chain link backstop being installed at baseball field", "name": "gallery-99-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-100-fence-project.webp", "alt": "Commercial fence posts being set along building wall", "name": "gallery-100-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-101-fence-project.webp", "alt": "Black vinyl-coated chain link fence along commercial property", "name": "gallery-101-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-102-fence-project.webp", "alt": "Black vinyl-coated chain link fence running along snowy hillside", "name": "gallery-102-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-103-fence-project.webp", "alt": "White vinyl privacy fence with double gate and black hardware", "name": "gallery-103-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-104-fence-project.webp", "alt": "White vinyl privacy fence installed along backyard in winter", "name": "gallery-104-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-105-fence-project.webp", "alt": "Green vinyl-coated chain link fence being installed at commercial lot", "name": "gallery-105-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-106-fence-project.webp", "alt": "White vinyl privacy fence in residential backyard with workers", "name": "gallery-106-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-107-fence-project.webp", "alt": "Horizontal wood-look composite privacy fence with dark metal posts", "name": "gallery-107-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-108-fence-project.webp", "alt": "White vinyl privacy fence along sandy beachfront property", "name": "gallery-108-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-109-fence-project.webp", "alt": "White vinyl privacy fence enclosing small residential backyard", "name": "gallery-109-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-110-fence-project.webp", "alt": "White vinyl picket fence around front yard", "name": "gallery-110-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-111-fence-project.webp", "alt": "White vinyl picket fence transitioning to privacy fence", "name": "gallery-111-fence-project", "type": "Vinyl" },
  { "path": "/img/gallery/gallery-112-fence-project.webp", "alt": "Pressure-treated wood deck frame under construction", "name": "gallery-112-fence-project", "type": "Wood" },
  { "path": "/img/gallery/gallery-113-fence-project.webp", "alt": "Galvanized chain link dumpster enclosure at commercial property", "name": "gallery-113-fence-project", "type": "Chain Link" },
  { "path": "/img/gallery/gallery-114-fence-project.webp", "alt": "Black vinyl-coated chain link fence in snowy conditions", "name": "gallery-114-fence-project", "type": "Chain Link" }
];

export const SERVICE_IMAGES = {
  wood: [
  {
    "path": "/img/gallery/gallery-01-cedar-privacy-fence.webp",
    "alt": "Tall cedar privacy fence installation by TWOMENS Fence in Delaware",
    "name": "wood-cedar-privacy-fence-tall"
  },
  {
    "path": "/img/gallery/gallery-02-wood-fence-with-gate.webp",
    "alt": "Pressure-treated wood privacy fence with gate installation in residential backyard",
    "name": "wood-privacy-fence-with-gate"
  },
  {
    "path": "/img/gallery/gallery-03-wood-privacy-backyard.webp",
    "alt": "New wood privacy fence installed along residential backyard property line",
    "name": "wood-privacy-fence-backyard"
  },
  {
    "path": "/img/gallery/gallery-04-porch-railing-complete.webp",
    "alt": "Completed wood porch railing with wood privacy fence in background",
    "name": "wood-porch-railing-complete"
  },
  {
    "path": "/img/gallery/gallery-19-crew-building-railing.webp",
    "alt": "TWOMENS crew installing custom wood porch railing on Delaware home",
    "name": "wood-porch-railing-crew-working"
  },
  {
    "path": "/img/crew/crew-working-railing.webp",
    "alt": "Fence installation crew building wood railing on residential porch",
    "name": "wood-porch-railing-crew-action"
  }
],
  vinyl: [
  {
    "path": "/img/gallery/gallery-06-vinyl-privacy-long.webp",
    "alt": "Long white vinyl privacy fence installation on open property in Delaware",
    "name": "vinyl-white-privacy-fence-long"
  },
  {
    "path": "/img/gallery/gallery-07-vinyl-privacy-residential.webp",
    "alt": "White vinyl privacy fence installed along residential property line",
    "name": "vinyl-white-privacy-fence-residential"
  },
  {
    "path": "/img/gallery/gallery-08-vinyl-privacy-house.webp",
    "alt": "White vinyl privacy fence installation alongside Delaware home",
    "name": "vinyl-white-privacy-fence-house"
  },
  {
    "path": "/img/gallery/gallery-09-vinyl-picket-house.webp",
    "alt": "White vinyl picket fence installation around residential property with yard",
    "name": "vinyl-white-picket-fence-house"
  },
  {
    "path": "/img/services/vinyl-fence-materials-prep.webp",
    "alt": "Vinyl fence materials being prepared for installation on job site",
    "name": "vinyl-fence-materials-prep"
  }
],
  chainlink: [
  {
    "path": "/img/gallery/gallery-12-chainlink-galvanized-field.webp",
    "alt": "Crew installing galvanized chain link fence on large property in Delaware",
    "name": "chainlink-galvanized-crew-install"
  },
  {
    "path": "/img/services/chainlink-black-vinyl-coated-commercial.webp",
    "alt": "Black vinyl-coated chain link fence with materials staged for commercial installation",
    "name": "chainlink-black-vinyl-coated-commercial"
  },
  {
    "path": "/img/gallery/gallery-10-chainlink-commercial-sports.webp",
    "alt": "Black chain link fence installation at commercial sports facility in Delaware",
    "name": "chainlink-black-commercial-sports"
  },
  {
    "path": "/img/gallery/gallery-11-chainlink-black-commercial.webp",
    "alt": "Long run of black vinyl-coated chain link fence around commercial property",
    "name": "chainlink-black-vinyl-coated-long"
  },
  {
    "path": "/img/gallery/gallery-13-chainlink-winter.webp",
    "alt": "Black vinyl-coated chain link fence installation in winter conditions",
    "name": "chainlink-black-winter-snow"
  },
  {
    "path": "/img/services/chainlink-commercial-fence-property.webp",
    "alt": "Commercial chain link fence with barbed wire on business property",
    "name": "chainlink-commercial-fence-property"
  },
  {
    "path": "/img/services/chainlink-posts-setting.webp",
    "alt": "Metal fence posts being set for chain link fence installation",
    "name": "chainlink-posts-setting"
  },
  {
    "path": "/img/services/chainlink-galvanized-field-long.webp",
    "alt": "Galvanized chain link fence stretching across large open field",
    "name": "chainlink-galvanized-field-long"
  }
],
  aluminum: [
  {
    "path": "/img/gallery/gallery-14-aluminum-ornamental.webp",
    "alt": "Black aluminum ornamental spear top fence installation in Delaware",
    "name": "aluminum-black-ornamental-spear-top"
  },
  {
    "path": "/img/gallery/gallery-15-aluminum-landscape.webp",
    "alt": "Black aluminum ornamental fence on beautifully landscaped property",
    "name": "aluminum-ornamental-fence-landscape"
  },
  {
    "path": "/img/services/aluminum-black-fence-posts-install.webp",
    "alt": "Black aluminum fence posts being installed with equipment on site",
    "name": "aluminum-black-fence-posts-install"
  }
],
  deck: [
  {
    "path": "/img/gallery/gallery-54-fence-project.webp",
    "alt": "Elevated pressure-treated wood deck with stairs and railing built by TWOMENS",
    "name": "deck-elevated-stairs"
  },
  {
    "path": "/img/gallery/gallery-55-fence-project.webp",
    "alt": "Composite deck with white vinyl railing nearing completion",
    "name": "deck-composite-railing"
  },
  {
    "path": "/img/gallery/gallery-31-fence-project.webp",
    "alt": "Composite deck build with railing in progress by TWOMENS crew",
    "name": "deck-build-progress"
  },
  {
    "path": "/img/gallery/gallery-93-fence-project.webp",
    "alt": "Pressure-treated wood deck joists and framing under construction",
    "name": "deck-framing"
  }
],
  tree: [
  {
    "path": "/img/gallery/gallery-20-crew-digging-posts.webp",
    "alt": "TWOMENS crew working on outdoor property project in Delaware",
    "name": "tree-crew-working"
  },
  {
    "path": "/img/crew/crew-deck-demolition.webp",
    "alt": "TWOMENS crew performing outdoor demolition and removal work",
    "name": "tree-crew-removal"
  }
],
} as const;

export const COMMERCIAL_IMAGES: SiteImage[] = [
  {
    "path": "/img/gallery/gallery-16-commercial-enclosure.webp",
    "alt": "Commercial chain link dumpster enclosure installation in parking lot",
    "name": "commercial-dumpster-enclosure-chainlink"
  },
  {
    "path": "/img/gallery/gallery-17-commercial-enclosure-winter.webp",
    "alt": "Commercial chain link enclosure installed at business property in winter",
    "name": "commercial-dumpster-enclosure-winter"
  },
  {
    "path": "/img/gallery/gallery-18-commercial-enclosure-night.webp",
    "alt": "Completed commercial chain link enclosure at night",
    "name": "commercial-chainlink-enclosure-nighttime"
  },
  {
    "path": "/img/gallery/gallery-07-vinyl-privacy-residential.webp",
    "alt": "Commercial chain link dumpster enclosure with swing gates",
    "name": "commercial-chainlink-dumpster-gates"
  },
  {
    "path": "/img/commercial/commercial-fence-posts-concrete.webp",
    "alt": "Commercial fence post installation with concrete footings along building",
    "name": "commercial-fence-posts-concrete"
  },
  {
    "path": "/img/commercial/commercial-fence-posts-alley.webp",
    "alt": "Commercial fence post setting in alley with concrete base",
    "name": "commercial-fence-posts-alley"
  },
  {
    "path": "/img/commercial/commercial-posts-bracing-alley.webp",
    "alt": "Commercial fence posts with bracing along brick building",
    "name": "commercial-posts-bracing-alley"
  },
  {
    "path": "/img/commercial/commercial-post-install-ladder.webp",
    "alt": "Commercial fence post installation with work truck and equipment",
    "name": "commercial-post-install-ladder"
  }
];

export const CREW_IMAGES: SiteImage[] = [
  {
    "path": "/img/gallery/gallery-20-crew-digging-posts.webp",
    "alt": "TWOMENS fence crew digging post holes for new fence installation",
    "name": "crew-digging-post-holes"
  },
  {
    "path": "/img/gallery/gallery-19-crew-building-railing.webp",
    "alt": "TWOMENS construction crew building custom porch railing",
    "name": "crew-building-porch-railing"
  },
  {
    "path": "/img/crew/crew-working-railing.webp",
    "alt": "Two crew members working together on porch railing installation",
    "name": "crew-working-railing"
  },
  {
    "path": "/img/crew/crew-deck-demolition.webp",
    "alt": "TWOMENS crew performing deck demolition and removal",
    "name": "crew-deck-demolition"
  }
];
